### PR TITLE
Add flag to update on upgrade

### PR DESCRIPTION
**Pull request by josegonzalez**
Heavily untested - does this even compile? - and I'm sure I'm missing something crucial here, like how to create an instance of `CommandLine`.

Opening for comments as I've seen code tend to be a better driver of progress than issues :)

Let me know how terrible my code is, and what I should be modifying.

Refs #7

### CODE REVIEW

**Comment by aaronfranke** [comment]
I believe you need to submit pull requests here https://anonscm.debian.org/git/apt/apt.git

**Comment by DonKult** [comment]
There is no inherent problem with a PR here, expect maybe that personally I am not too closely following github. Note that in Debian alioth is being replaces by salsa at the moment, so if at all you can consider https://salsa.debian.org/apt-team/apt an alternative contact point. Or your mailinglist deity@lists.debian.org. Or our IRC channel #debian-apt on OFTC. Or all of the previously mentioned :) .

That said, the feature itself might be interesting but really needs a good plan and lots of code (perhaps not new, but moving). I wouldn't consider this a good first-time bug, but with enough motivation everything is possible (my first few contributions weren't exactly first-timer-bugs either) – and we are happy to help if any specific questions arise to make it work.

This PR doesn't even build at the moment through, so I am unsure how to help. It looks like Jose didn't even get apt to build locally judged by multiple commits fixing syntax errors of previous ones but without details there isn't much I can do and the others probably felt the same way.

**Comment by josegonzalez** [comment]
It's been a while since I looked at this, but my intention here was to somehow create a dummy `CommandLine` object and pass it into `DoUpdate()`. `DoUpdate()` Takes a single `CommandLine` object and verifies that no arguments were passed - why isn't argument checking done upstream of the command? - so giving it a dummy one seemed like a reasonable idea.

The alternative is to create a `DoUpdate()` that takes no args and does the check, and have a `PerformUpdate()` which is called from that. Then the `PerformUpdate()` can be called from `DoUpgrade()` instead.

I'll try that I think.

**Comment by aaronfranke** [comment]
What is the end goal here? My preference would be for `full-upgrade` to also include `update`. Or perhaps there would be a new `full-update` so we can leave `full-upgrade` as it is? 

Adding a flag as in the title is not ideal IMO. The goal is to have a *simpler* method to `update` and `full-upgrade`. Two args is harder to remember than just typing one arg.

**Comment by josegonzalez** [comment]
So I would like to have `update` on `upgrade` as well as on `install`.

What is the difference between `upgrade` and `full-upgrade`?

**Comment by josegonzalez** [comment]
@DonKult ideas as to how I might introduce some unit testing here? Do I just copy [this](https://github.com/Debian/apt/blob/master/test/integration/test-apt-update-file) and change all the `aptget update` calls to `aptget upgrade --update`? Not sure about unit tests either.

**Comment by aaronfranke** [comment]
If you don't know the difference between `upgrade` and `full-upgrade` then maybe you shouldn't be writing this patch. `full-upgrade` is basically just like `dist-upgrade`. In addition to updating packages, it may remove packages in order to do more updates.

**Comment by DonKult** [comment]
> why isn't argument checking done upstream of the command?

It is – kind of. The commandline is parsed before the commands are called (otherwise, how would apt know what command to call), but while options, flags and co are taken care of, some things remain on the commandline to be taken care of by the command as it depends on what the command wants to do how to interpret them. `update` has no such arguments (at the moment), but e.g. `install` has in the form of package names to install. But it could also be filenames of deb files. Or the package names have modifiers attached, … so command has to deal with those. Similar for other commands like `build-dep`, `show` or `remove`.

Instead of a dummy I guess I would just use the existing one and split DoUpdate so that the method you call isn't including the check for non-parameters. We can "worry" about how to deal with parameters if update ever gets some.

> What is the difference between upgrade and full-upgrade?

full-upgrade can remove packages in the solution, the upgrade command(s) can't. See the apt and apt-get manpages for details (full-upgrade is also called dist-upgrade).

> What is the end goal here?

There is no need to do everything at once. A flag which could be made to apply for all commands would be a good first step. We could then look into providing ways to activate/deactivate it in certain conditions (time since last update, …) which would likely be better than just running it all the time.

> ideas as to how I might introduce some unit testing here?

Just to prevent confusion: integration tests is what you talk about by referring to one of the scripts. We have unittests as well, but such a flag is unlikely to be wellsuited for one as they deal more with checking "simple" more or less standalone functions only. Back to integration tests: Modifying an existing one might be simplest. Find one which does an `update` and then an `upgrade` and change it accordingly. Or you can just write a new one. Copying the upper part of test-apt-update-simple might be a good idea. As you want to upgrade you will need an installed package: insertinstalledpackage will help you with this.

**Comment by josegonzalez** [comment]
@aaronfranke I almost certainly shouldn't be writing this patch, but given that no one else attempted to, I figured I could spend some time on the issue before calling it quits.

@DonKult I split out the login in `DoUpdate()` into a `PerformUpdate()`, seems to at least pass tests :D

I'll take a look at the integration tests in a bit, good call on finding one that does both and combining them. Totally overlooked that.

Can take a stab at unit tests once I get _a single_ integration test written :)

Once this is done, I can resubmit on the `salsa` site if that would be preferred. I have zero clue as to how to submit to alioth - email patches? - but happy to attempt that once this is in a mergeable state.

**Comment by DonKult** [comment]
> I can resubmit on the salsa site if that would be preferred

as said above, no need to, we follow github as well. Reponse time is more a matter of being lucky to reach someone with a bit of free time than using a specific channel to reach one of us.

**Comment by julian-klode** [comment]
GitHub has the huge advantage of running CI on pull requests - have not set that up on salsa yet :)

**Comment by josegonzalez** [comment]
I don't have much time to follow up on this PR, so I'll be closing this for now. Hopefully this sort of feature comes along in the future :)

**Pull request closed without merging**
