### PR TITLE
autoclean: Add autoclean to bash completion

### PR DESCRIPTION
**Pull request by api-walker**
This shows the autoclean command in the bash completion.

### CODE REVIEW

**Comment by julian-klode** [comment]
Thanks for the pull request. It's a bit strange to add autoclean without clean, and it's also an entirely different category than install/remove/etc, so it should be on a separate line.

There are probably other commands we have to add as well :(

**Comment by api-walker** [comment]
I tried to add all, by me known, commands and sort it right.

**Comment by api-walker** [comment]
I added the package forecast like in apt-get. What is left to be done?

**Comment by julian-klode** [comment]
Thanks. Two comments:

(1) source and build-dep should also have source packages as in apt-get
(2) download and changelog can be merged into show|list
(3) rebase against master and squash everything in one or two logical commits (maybe one for the simple cases like download, changelog, clean; and one for the source and build-dep stuff)

Apart from that it looks great, and it would be wonderful to have. Thank you.

**Comment by api-walker** [comment]
Glad to hear that you like it. But one problem, I don't know how to rebase with git. Can you give me a hint, please? Thank you.

**Pull request closed without merging**
