### PR TITLE
typofix - https://github.com/vlajos/misspell_fixer

### PR DESCRIPTION
**Pull request by vlajos**

### CODE REVIEW

**Comment by mvo5** [comment]
Thanks a bunch! This is great stuff, thanks for going through the code and fixing the misspellings. I need to review it carefully to see if any public API has changed next :)

**Comment by aaronfranke** [comment]
Is printHashSumComarison referenced anywhere else? It may be the reason why it failed to build. Try submitting just the plain text (non-code) changes to its own pull request.

**Comment by vlajos** [comment]
I see only 2 references and both have been fixed in this patch.
Anyway let me know please if I can help/modify anything.

**Comment by julian-klode** [comment]
Commit rebased with an updated commit message and merged as
commit 8d89cda7d66b6f125c457f36beeb84abb0df07f1

**Pull request closed without merging**
