### PR TITLE
Fix typo inside russian error message translation

### PR DESCRIPTION
**Pull request by yakunink**
Hello,
I've found typo inside translation.

"и поэтому потенциально **из** небезопасно использовать." - means nothing in Russian.
Correct way to write is: "и поэтому потенциально **их** небезопасно использовать."

Many thanks for linux-distribution you make.

Happy hacktoberfest,
Konstantin

### CODE REVIEW

**Comment by julian-klode** [comment]
I don't speak Russian, but I see the same word in the first half. Is it correct there?

**Comment by yakunink** [comment]
This is ok. "из" - means "from", and "их"  is a pronoun meaning "them, they, their, it". If you translate back from Russian this part of sentence: "и поэтому потенциально их небезопасно использовать." it will be some thing like: "and thats why it is potentially not safe to use **it**"

**Comment by DonKult** [comment]
Hi yakunink!

Thanks for the patch! Unfortunately I can't speak Russian either, so doing a honest review on the change is rather hard and it isn't really how we work with translations usually so I worry we might loose the fix again accidently…

May I suggest you contact the last translator Aleksej Shilin (the contact address is noted at the top of the po files in the Last-Translator field)? Perhaps he is working on an update at the moment causing us to loose the fix again later as applying patches on po-files isn't our usual translation workflow: Applying patches on po-files is rather hard, so usually we take in translations as complete files from our translators which we don't review (above simple syntax checks) as they are reviewed by the language teams (contact also noted in the header section).

Joining a language team is a great way of contributing to Debian (and all its derivatives) btw.

**Comment by DonKult** [comment]
Hi,

as noted in my previous comment, this PR can't really be merged as this isn't how we work with translations, so I close it now for housekeeping reasons. I see that we haven't seen an update of the ru.po file so far. If you had contacted the previous translator and he hasn't responded by now it might be a good idea to talk to the language team and adopt the translation as the new translator.

I am looking forward to seeing an updated ru.po file proposed in the future in any case!

**Pull request closed without merging**
