### PR TITLE
Expanded search using a string-matching algorithm 

### PR DESCRIPTION
**Pull request by Ziul**
To force a search using regex, use the flag `--using-regex`, otherwise, the
search is done using the **Rabin-Karp** algorithm, giving some memory free
and more faster search (Rabin-Karp is almost 1/3 faster than Regular Expression with this hash). Any search with the characters `^$*+?()[]{}\\|`  is done using regex search.

With the  support to multiple order  yet:
 -   Alphabetic [default]
 -   Reverse Alphabetic
 -   Status
 -   Version

### CODE REVIEW

**Comment by Arthur2e5** [comment]
I don't think Debian guys will ever look at this repo. Consider sending https://github.com/Debian/apt/pull/8.patch to the [bug tracking system](https://www.debian.org/Bugs/) via email.

PS: Given that this sounds like a breaking change, you may want to add a `--literal-match` options or something like that instead.

**Comment by julian-klode** [comment]
We surely do from time to time (not all of us, though). But we're not merging any features currently.

I also strongly reject the --regex patch. 33% faster search is not important enough to break things or have this amount of complication.I also do not see

**Comment by Ziul** [comment]
The flag was just to force the search as a regex. If a search is done using any of the following characters: `^$*+?()[]{}\\|`, is identified as a regex search automatically. The flag was to support regex searches using the ones like `.,:` that normally contains into the package's name. Anyway, i updated the flag from ` --regex` to `--using-regex`.  Also did a **rebase** with master so i can update the branch of the pull request. Thanks by the tip @Arthur2e5.

**Comment by Arthur2e5** [comment]
Ugh……I don't think you got the right ref to rebase…
Oh I see……This PR points to `debian/exp` while your rebase is for `master`.

**Comment by Ziul** [comment]
yeap...would change the PR to `master`, as they wasn't using it some months ago...but looks like i cannot change the destiny's branch of the PR after open.  Fixed.

**Pull request closed without merging**
