### PR TITLE
Search packages with order-by feature

### PR DESCRIPTION
**Pull request by Ziul**
#### Included support to search packages into CLI ordered by:

-   Alphabetic [default]
-   Reverse Alphabetic
-   Status
-   Version

### CODE REVIEW

**Comment by Ziul** [comment]
@DonKult Could you please give me some feedback about this new pull request? I'm trying to keep it updated with the debian/experimental, so many of yours commits shows up.

**Comment by DonKult** [comment]
Hi,

I am not sure how you "trying to keep it updated", but it looks like you are rebasing debian/experimental on your pull-request instead of the other way around, because the hashes from my/mvos commits don't match with /experimental anymore, so merging your commits means remerging ours (which fails).
With some git magic I got a slightly more readable diff compared to the one github offers me… anyway some comments (as with my previous comments: --order-by=random):

> addArg(0, "order-by", "APT::Cache::OrderBy", 1);

Why are you using a magic constant here? No other place in the file does, so I wonder where you got the idea from. Anway: CommandLine::HasArg is what you should write instead of 1.

Some of your new lines have trailing whitespaces. Please remove them. We have enough of those already. ;)

Sorting by status… I am not sure. In the alphabet I am sure which letter follows another, but in the status… that is an order type which would need a long and explicit documentation so that the order doesn't look random. Doesn't seem worth it in my eyes, but maybe @mvo5 can tell us why he mentioned it in the initial FIXME. Frankly, I am not even sure what the point of sorting by version is. Maybe we should just go with alphabetic by default and a --reverse flag…

Apropos documentation: I don't see any. ;)

apt-private/private-package-info.cc has a gazillion includes: Are these really all needed?
.h has in return not a single one, even through you clearly need e.g. string.

> PackageInfo pkg(CacheFile, records, V, outs.str());
> outputVector.push_back(pkg);

prefer "outputVector.emplace_back(CacheFile, records, V, outs.str());" in C++11 code as it avoids a temporary object for sure rather than rely on the compiler to optimize it out (not that it would matter here).

> std::sort(outputVector.begin(), outputVector.end(), OrderByReverseAlphabetic);

I am relatively sure you can achieve the same with
std::sort(outputVector.rbegin(), outputVector.rend(), OrderByAlphabetic);
saving us from implementing the same order twice, just reversed (not that it would be immensely complicated, but less is good)

"hashit" is an awful name for a function, even in our private set. Some sensible name would be better – and maybe move it into PackageInfo as a static method. I think the OrderBy functions would be better as static methods as well.

The format member of PackageInfo is never used apart from its getter/setter (which themselves are never used).

A pull-request with a test which even passes… Love it. The PR looks good in general, even if I comment on many small things, so please don't get the impression I would be ripping it apart entirely. Pocking me is just like pocking a wasps nest… ;)


But enough nitpicks for the moment, lets see what mvo has to say first.

**Comment by Ziul** [comment]
Hi!
> I am not sure how you "trying to keep it updated", but it looks like you are rebasing debian/experimental on your pull-request instead of the other way around, because the hashes from my/mvos commits don't match with /experimental anymore, so merging your commits means remerging ours (which fails).

Strange... Some commits ago the github show a conflict from my pr with /experimental. So i just `pull --rebase` /experimental with my branch and was fast-forwarded. Than so github pass it with ok as it's now. But nothing that a cherry-pick couldn't solve.

> Why are you using a magic constant here?

My bad! Soon after mvo5 give hist feedback i should fix it.

> Some of your new lines have trailing whitespaces.

Damn! still thos ones? Review than i will!

> Apropos documentation:

My bad[2]! I'll update it. Should be in this [file](https://github.com/Debian/apt/blob/debian/experimental/doc/apt.8.xml) right? Planing to let it simmillar with the `list` option.

> apt-private/private-package-info.cc has a gazillion includes: Are these really all needed?

Probably not. I'll try to clean it after the feedback.

> prefer "outputVector.emplace_back(CacheFile, records, V, outs.str());"

Nice tip! Didn't know that one.

> I am relatively sure you can achieve the same with std::sort(outputVector.rbegin(), outputVector.rend(), OrderByAlphabetic); saving us from implementing the same order twice

Unfortly, the default order from cache means sort into the `source.list` and than into alphabetic, which means isn't the alphabetic at all. As in the beginner was using `maps`, it was transparent.

> "hashit" is an awful name for a function, even in our private set. Some sensible name would be better – and maybe move it into PackageInfo as a static method. I think the OrderBy functions would be better as static methods as well.

Note taked! Wasnt so inpiraded to name that `hashit`.

> The format member of PackageInfo is never used apart from its getter/setter

The ideia was use `_format` to overwrite the `<<` operator. Probably in the soons pr i should use it more. I hope in the end could offer something like `axi-cache` does when you look for "gyt" instead "git"

**Comment by DonKult** [comment]
Quicknote:
>> I am relatively sure you can achieve the same with std::sort(outputVector.rbegin(),
>> outputVector.rend(), OrderByAlphabetic); saving us from implementing the same order twice
>
> Unfortly, the default order from cache means sort into the source.list and than into alphabetic, which > means isn't the alphabetic at all. As in the beginner was using maps, it was transparent.

I think you misunderstood me: I meant the line "std::sort(outputVector.begin(), outputVector.end(), OrderByReverseAlphabetic);" which I think can be replaced with "std::sort(outputVector.rbegin(), outputVector.rend(), OrderByAlphabetic);" rendering OrderByReverseAlphabetic unneeded as the 'heavy-lifting' is done by standard c++.

**Comment by Ziul** [comment]
Updated request into #8. Squashed my commits into two only. The first contains the feedback over here, the second have new improvements.

**Pull request closed without merging**
