### PR TITLE
fix typo in polish --help

### PR DESCRIPTION
**Pull request by arteq**

### CODE REVIEW

**Comment by DonKult** [comment]
Hi,

as you might suspect, reviewing changes in po files is hard if you don't speak the language yourself. As a project native to Debian we therefore defer such reviews and the maintenance of the po files for the respective languages in general to designated maintainers (= translators) and the language team. In the file the maintainer is mentioned as "Last-Translator", the language team just below that, in this case: debian-l10n-polish@lists.debian.org.

It would be good if you could contact the team and the maintainer with your changes so they can review, check e.g. for house style (= in english that would be stuff like oxford comma or not) and help with things in general.

Note though that the translator hasn't updated the file in a long while (2012), so they might be MIA. I don't see that much activity in the language team mailinglist either – so they might need some new contributors: you perhaps? Either way, please contact both by mail first, depending on the reply (or not) we will figure something out.

**Comment by arteq** [comment]
Hi,
sure thing, I will try to reach out to the last translator and the i10n
list if that fails (although the last post on that list is May 2019...).

Thanks.

-- 
Artur

pt., 17 kwi 2020 o 21:49 David Kalnischkies <notifications@github.com>
napisał(a):

**Comment by arteq** [comment]
Hello,
sorry for the delay. The last translator said to go ahead and gave green light, so I think you can merge that. In case you need some proof/confirmation we can replay our conversation in debian-l10n-polish@lists.debian.org.

**Comment by DonKult** [comment]
Thanks for checking! I have no problem with merging it then, no need for replay.

One question through: I am not that well versed in github, so is "ArteQ <arteq@users.noreply.github.com>" the moniker and mail address this contribution should be recorded and attributed as or is it just some default & you would prefer something else?

(We have no realname policy, requirements for reachable addresses or anything, so it is fine either way from my PoV)

**Comment by arteq** [comment]
Hi,
that was some auto-generated email from github, so please use this instead wherever appropriate:

Artur Grącki <arteq@arteq.org>

**Comment by DonKult** [comment]
Committed upstream: https://salsa.debian.org/apt-team/apt/-/commit/d0e46fe7e8562953ced76fe938fb5ff1f0774be7

Thanks!

**Pull request closed without merging**
