### PR TITLE
Only call _filedir if we're completing something that apt will know to install.

### LINKED ISSUE #28: apt install of local debs does not tab-complete
this fails:
```
$ touch xyzzy.deb
$ apt install xyzzy<tab>
```
because the completion support for install is using `_filedir` wrong.

### PR DESCRIPTION
**Pull request by chipaca**
Resolves #28.

### CODE REVIEW

**Comment by julian-klode** [comment]
Seems to work. The commit message needs some work though - the summary should be more human readable (Something like "bash-completion: Only complete understood file paths for install") and there should be a long description.

Also please add `fixes #28` somewhere in the long description so merging it closes the bug, and add

"LP: #1645815"

as the last line of the message (separated from description prose by an empty line), so we close the launchpad bug (which I just reopened again) as well. Given that this is a tiny fix, it's likely I'll include this in upcoming stable releases in 1.3/yakkety and 1.2/xenial as well, although likely not the next ones, as they contain bugfixes upto 1.4 beta1 for now.

**Comment by chipaca** [comment]
@julian-klode just to clarify, you want me to `git --amend` and push, right?

**Comment by julian-klode** [comment]
Yes :)

**Comment by chipaca** [comment]
Do I need to do anything further?

**Comment by julian-klode** [comment]
Eww, sorry, I did not receive any notification about the push from github. Looks good to me.

**Pull request merged**
