### PR TITLE
Review of the italian translations

### PR DESCRIPTION
**Pull request by freetom**
Improved the translations by:
* Fixing mistakes
* Improving readability
* Adding missing translations

Signed-off-by: Tomas Bortoli <tomasbortoli@gmail.com>

### CODE REVIEW

**Comment by julian-klode** [comment]
It would be great if you could coordinate your translations with the responsible translation team. The relevant maintainer here seems to be the Milo Casagrande <milo@milo.name> and the mailing list tp@lists.linux.it, but there's also debian-l10n-italian@lists.debian.org.

We can't just merge translations from GitHub that have not been reviewed by the teams, that would cause quite some uproar, and well, inconsistencies between translations - imagine aptitude and apt using different words for the same things :(

**Comment by julian-klode** [comment]
Oh, it fails CI:
/home/travis/build/Debian/apt/build/po/locale/it/LC_MESSAGES/apt-utils.po:121: 'msgid' and 'msgstr' entries do not both end with '\n'

Also, the short commit message should be "Italian program translation update", the long one is OK.

I just figured out @MiloCasagrande is on GitHub too, so let's see if we can get that done :)

**Comment by julian-klode** [comment]
And of course, if you fix one of the fuzzy strings, you also need to remove the ", fuzzy" tag from it.

**Comment by MiloCasagrande** [comment]
Yes, I'm here.

Truth be said, I was also working on completing the apt translation (along with others I maintain).

It would have been better to contact at least the mailing list before starting to work on this, one of use here sort of wasted their time. I usually get emails with suggestions or typos to fix and incorporate those promptly.

I would prefer to take it offline at this point and discuss with Tomas his suggestions/changes and then go through the upload process again.

@julian-klode What is the blessed way of sending the translations? Should we stick to opening a Debian bug and go through the default process?

**Comment by julian-klode** [comment]
@MiloCasagrande I don't really care that much, sometimes I forget about GitHub stuff, but sometimes it's easier :)

**Comment by freetom** [comment]
Hi Milo, yes sure we can coordinate a merge of our translations.. 

I just noticed that the IT messages in APT are pretty incomplete.. so I decided to commit to it. Not that much work for a mothertongue ;)

**Comment by MiloCasagrande** [comment]
@freetom I can take the PO file from your repo and compare it side by side with what I have, I only have 10 fuzzies left to go through on my copy. Working with the diff of PO files is impossible due to the usually many source code line changes, that makes my life harder.

Please next time contact either the last maintainer or the mailing list before, it's much easier that way.

**Comment by DonKult** [comment]
Commit 2bcc73f4392136a702f5e3dd9234addefd8a7f9c is an update for the po/it.po by Milo which as outlined by the previous comments is our authority in terms of Italian program translations updates.

I am hence considering this PR to be done/merged. If there is still something missing/discussion-worthy I am sure those can be resolved between you two & the language team. Thanks for your work & contribution and best regards!

**Pull request closed without merging**
